name: Deploy

env:
  ENVIROMENT: green

on:
  push:
    branches: [main]

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run typescript type check
        run: npm run lint:types

      - name: Run tests
        run: npm test

  build-container:
    name: Build container
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          envkey_REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
          file_name: .env.local

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shatynska/dro-psypra-com:latest

  redeploy:
    name: Redeploy stack to Portainer
    runs-on: ubuntu-latest
    needs: build-container

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Redeploy stack
        uses: luminos-company/portami@v1.2
        with:
          endpoint: 'https://admin.psypra.com'
          access_token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          stack_name: 'dro_psypra_com_${{ env.ENVIROMENT }}'
          file_path: '.github/stack/${{ env.ENVIROMENT }}.yml'
          prune: true
          pull: true
